# -*- coding: utf-8 -*-
"""EcoSat-Regression-Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vFHslMZjfOjN1SUefw-laudpQ99Fq3FB
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import pandas as pd

PATH = '/content/yolov5_v3_alldata.csv'

df = pd.read_csv(PATH).drop_duplicates()

num_rows = df.index.size

train_len = (int)(0.75*num_rows)

print(train_len)

df_train = df.sample(train_len, ignore_index=True)

df_tuples = set(df.apply(tuple, axis=1))
df_train_tuples = set(df_train.apply(tuple, axis=1))

df_test_tuples = df_tuples - df_train_tuples
df_test = pd.DataFrame(list(df_test_tuples), columns=df.columns)


print(df_train)
print(df_test)

X_train = df_train[["Max Chimneys", "Average Chimneys", "Average Area", "Avg Color/Pixel", "Avg Conf/Pixel"]]
X_test = df_test[["Max Chimneys", "Average Chimneys", "Average Area", "Avg Color/Pixel", "Avg Conf/Pixel"]]
print(X_train)
print(X_test)

y_train = df_train["Actual Emissions"]
y_test = df_test["Actual Emissions"].to_numpy()

print(y_train)
print(y_test)

import pandas as pd

df_train = pd.read_csv("/content/yolov5_v3_train.csv")
X_train = df_train[["Max Chimneys", "Average Chimneys", "Average Area", "Avg Color/Pixel", "Avg Conf/Pixel"]]
y_train = df_train[["Actual Emissions"]]

df_test = pd.read_csv("/content/yolov5_v3_test.csv")
y_test = df_test[["Actual Emissions"]].to_numpy()
X_test = df_test[["Max Chimneys", "Average Chimneys", "Average Area", "Avg Color/Pixel", "Avg Conf/Pixel"]]

import tensorflow as tf
from tensorflow.keras.optimizers import Adam
from keras.callbacks import EarlyStopping

model = tf.keras.Sequential([
    tf.keras.layers.Dense(500, activation='relu', input_shape=(5,)),
    tf.keras.layers.Dense(500, activation='relu'),
    tf.keras.layers.Dense(500, activation='relu'),
    tf.keras.layers.Dense(500, activation='relu'),
    tf.keras.layers.Dense(500, activation='relu'),
    tf.keras.layers.Dense(500, activation='relu'),
    tf.keras.layers.Dense(500, activation='relu'),
    tf.keras.layers.Dense(500, activation='relu'),
    tf.keras.layers.Dense(1)  # Output layer for regression, no activation function
])


early_stopping_monitor = EarlyStopping(
    monitor='val_loss',
    min_delta=0,
    patience=200,
    verbose=0,
    mode='auto',
    baseline=None,
    restore_best_weights=True
)
#0.0005, 3000 is best
# Compile the model
model.compile(optimizer=Adam(learning_rate=0.000075), loss='MeanSquaredLogarithmicError')

# Train the model
model.fit(X_train, y_train, epochs=3000, batch_size=2, validation_split=0.1)

import tensorflow as tf
model = tf.keras.models.load_model('/content/drive/Shareddrives/1:1_Krish_Arora/EcoSat/Regression/Models/yolov5_v3_lr_0.0005_ep_3000_bs_2')
model.summary()

preds = model.predict(X_test)
preds

preds = preds.reshape(-1)

max_accuracy = 0
min_accuracy = 100
results = []
accuracies = []
for i, pred in enumerate(preds):
  actual = y_test[i]
  accuracy = 100-100*abs(pred-actual)/actual
  if accuracy > max_accuracy:
    max_accuracy = accuracy
  if accuracy < min_accuracy:
    min_accuracy = accuracy
  results.append((df_test.iloc[i]["Facility Id"],round(accuracy,3)))
  accuracies.append(round(accuracy,3))

print(results)
print(round(sum(accuracies)/len(accuracies),3))
print(max_accuracy)
print(min_accuracy)

preds = preds.reshape(-1)

max_accuracy = 0
min_accuracy = 100
results = []
accuracies = []
for i, pred in enumerate(preds):
  actual = y_test[i]
  accuracy = 100-100*abs(pred-actual)/actual
  if accuracy > max_accuracy:
    max_accuracy = accuracy
  if accuracy < min_accuracy:
    min_accuracy = accuracy
  results.append((df_test.iloc[i]["Facility Id"],accuracy))
  accuracies.append(accuracy)

print(results)
print(sum(accuracies)/len(accuracies))
print(max_accuracy)
print(min_accuracy)

df_train.to_csv("yolov5_v3_train.csv")
df_test.to_csv("yolov5_v3_test.csv")

predictions = []

for i, pred in enumerate(preds):
  predictions.append([y_test[i],pred])

predictions

from sklearn.metrics import mean_squared_error

mean_squared_error(y_test,preds,squared=False)#returns root mean squared error

from sklearn.metrics import mean_absolute_error

mean_squared_error(y_test,preds)

from sklearn.metrics import mean_absolute_percentage_error

mean_absolute_percentage_error(y_test,preds)*100

from sklearn.metrics import mean_squared_log_error

mean_squared_log_error(y_test,preds)

model.save("/content/drive/Shareddrives/1:1_Krish_Arora/EcoSat/Regression/Models/yolov5_v3_lr_0.000075_ep_3000_bs_2")

def create_model(base_model, num_classes):
    import tensorflow as tf
    # Grab the last layer and add a few extra layers to it
    x=base_model.output

    # Dense layers
    x=tf.keras.layers.Dense(3,activation='relu', kernel_initializer=tf.keras.initializers.VarianceScaling(), use_bias=True)(x) #first num is num inputs
    x=tf.keras.layers.Dense(100,activation='relu', kernel_initializer=tf.keras.initializers.VarianceScaling(), use_bias=True)(x) #first num is num inputs

    # Final layer with softmax activation
    preds=tf.keras.layers.Dense(num_classes,activation='relu', kernel_initializer=tf.keras.initializers.VarianceScaling(), use_bias=False)(x)

    # Create the final model
    model=Model(inputs=base_model.input,outputs=preds)
    return model

def get_optimizer(optimizer_name, learning_rate):
    # Import keras optimizers
    from tensorflow.keras.optimizers import Adam, Adadelta, Adagrad, Adamax, Ftrl, Nadam, RMSprop, SGD
    print('Selected Optimizer', optimizer_name)
    switcher = {
        'Adadelta': Adadelta(lr=learning_rate),
        'Adagrad': Adagrad(lr=learning_rate),
        'Adam': Adam(lr=learning_rate),
        'Adamax': Adamax(lr=learning_rate),
        'FTRL': Ftrl(lr=learning_rate),
        'NAdam': Nadam(lr=learning_rate),
        'RMSprop': RMSprop(lr=learning_rate),
        'Gradient Descent': SGD(lr=learning_rate)
    }
    # If optimizer_name is empty, Adam will be return as default optimizer
    return switcher.get(optimizer_name, Adam(lr=learning_rate))

# Import packages needed to create a imaage classification model
import matplotlib.pyplot as plt
import numpy as np
import os
import tensorflow as tf #core package

from keras.applications.resnet import preprocess_input #keras is the way to tensorflow
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import Dense,GlobalAveragePooling2D
from keras.models import Model
from tensorflow.keras import regularizers

from tensorflow.keras.preprocessing import image_dataset_from_directory
from keras.callbacks import EarlyStopping
from tensorflow import keras

# Initialize hyper params
epochs = 50 #<-- increase for higher accuracy
base_learning_rate = 0.001 #decrease for different results; use excel sheet to note down results from each change to learning rate and epochs
optimizer = 'Adam'
BATCH_SIZE = 32

IMG_SIZE = (224, 224)





# Specify the number of classes
num_classes = 1

# Create the base model
model = create_model(base_model,num_classes)

print(len(base_model.layers))

model.compile(optimizer = get_optimizer(optimizer_name=optimizer,learning_rate=base_learning_rate),loss='CategoricalCrossentropy',metrics=['accuracy'])
# Adam optimizer
# loss function will be categorical cross entropy
# evaluation metric will be accuracy

early_stopping_monitor = EarlyStopping(
    monitor='val_loss',
    min_delta=0,
    patience=30,
    verbose=0,
    mode='auto',
    baseline=None,
    restore_best_weights=True
)

step_size_train = train_generator.n//train_generator.batch_size
history_fine = model.fit(train_generator,
                        epochs=epochs,
                        callbacks=[early_stopping_monitor],
                        validation_data = validation_generator,
                        verbose=1)
#ran frist of 20 epocs, measures accuracy for each epoch. model.fit is when training happens

model.save('/content/drive/Shareddrives/1:1 Krish Arora/mobileNetV2_hyper_param.h5')

# Import numpy for calculating best model accuracy
import numpy as np
# Populating matrics -> accuracy & loss
acc = history_fine.history['accuracy']
val_acc = history_fine.history['val_accuracy']

loss = history_fine.history['loss']
val_loss = history_fine.history['val_loss']

print('Training Accuracy: ', acc)
print('Validation Accuracy: ', val_acc)
print('Training Loss: ', loss)
print('Validation Loss: ', val_loss)
best_model_accuracy = history_fine.history['val_accuracy'][np.argmin(history_fine.history['val_loss'])]
print('best model accuracy: ', best_model_accuracy)

"""# Predicting code for an image
from tensorflow.keras.preprocessing import image
# Please replace the brackets below with the location of your image which need to predict
img_path = '<>'
img = image.load_img(img_path, target_size=IMG_SIZE)
img_array = image.img_to_array(img)
img_batch = np.expand_dims(img_array, axis=0)
img_preprocessed = preprocess_input(img_batch)
prediction = model.predict(img_preprocessed)
print(prediction)

Create Plot
"""

import matplotlib.pyplot as plt
import numpy as np

# show model accuracies
plt.plot(history_fine.history["val_accuracy"])
plt.plot(history_fine.history["accuracy"])
plt.title("Survival Time Model: Accuracy")
plt.ylabel("Accuracy (%)")
plt.xlabel("Epoch")
plt.legend(['Validation','Train'], loc='lower right')
plt.show()

# show model losses
plt.plot(history_fine.history["val_loss"])
plt.plot(history_fine.history["loss"])
plt.title("Survival Time Model: Loss")
plt.ylabel("Loss")
plt.xlabel("Epoch")
plt.legend(['Validation','Train'], loc='upper right')
plt.show()

"""Generate confusion matrix"""

# TF model predicitons
from sklearn.metrics import classification_report, confusion_matrix

Y_pred = model.predict_generator(validation_generator) #gets all the predictions(probabilities) from ai
print(Y_pred)

# Extract the predicions as numbers
y_pred = np.argmax(Y_pred, axis=1)
print(y_pred)

y_truth = validation_generator.classes #gets the real labels.

#y_truth is the ground truth labels
#y_pred are the predictions
print(confusion_matrix(y_truth, y_pred))

"""Extract label names"""

label_names = list(train_generator.class_indices.keys())

"""Create report with more metrixs"""

print('Classification Report')
print(classification_report(y_truth, y_pred, target_names=label_names))

"""Creating stacked images"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
from PIL import Image
from pylab import *
from mpl_toolkits.mplot3d import Axes3D

img1 = cv2.imread("2018-03-14.jpg")

img2 = cv2.imread("2018-01-23.jpg")

#stack = np.stack([img1,img2]).reshape(3,3)
#im = Image.fromarray(stack)
#im.save("your_file.jpeg")


x, y = ogrid[0:img1.shape[0], 0:img1.shape[1]]
ax = gca(projection='3d')
ax.plot_surface(x,y,10,rstride=5,cstride=5,facecolors=img1)
show()

import matplotlib.pyplot as plt
import numpy as np
import cv2
img1 = cv2.imread("2018-03-14.jpg")

ax = plt.figure().add_subplot(projection='3d')
res = cv2.resize(img1, dsize=(0.1, 0.1), interpolation=cv2.INTER_CUBIC)
ax.plot(2,2, zs=100, zdir='z', label='curve in (x, y)')
ax.imshow(res)

# Import ImageIO and NumPy
import imageio
import numpy as np

# Read in each 2D image
img1 = imageio.imread('2018-01-23.jpg')
img2 = imageio.imread('2018-02-27.jpg')

# Stack images into a volume
vol = np.stack([img1,img2])
print('Volume dimensions:', vol.shape)